FROM ruby:2.6.0

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN apt-get update && apt-get install -y nodejs && bundle install
COPY . /usr/src/app

CMD rails db:migrate && rails s
